# yaml-language-server: $schema=https://raw.githubusercontent.com/the-database/traiNNer-redux/refs/heads/master/schemas/redux-config.schema.json
#########################################################################################
# ParagonSR Enhanced OTF Training Configuration with Sequence Control
# Added by Philip Hofmann for Realistic Photography Workflow Simulation
#########################################################################################

name: %scale%_%archname%_paragon_sr_enhanced_sequences
scale: %scale%
use_amp: true
amp_bf16: false
use_channels_last: true
fast_matmul: false
num_gpu: auto
# manual_seed: 1024

########################################################################################################################
# Dataset and Dataloader Settings for ParagonSR with Enhanced Sequence Control
########################################################################################################################
datasets:
  train:
    name: ParagonSR Training Dataset (Enhanced Sequences)
    type: realesrgandataset
    dataroot_gt: [
      datasets/train/dataset1/hr,
      datasets/train/dataset1/hr2
    ]
    lq_size: %lq_size%
    use_hflip: true
    use_rot: true

    num_worker_per_gpu: 8
    batch_size_per_gpu: %batch_size_per_gpu%
    accum_iter: %accum_iter%

  val:
    name: ParagonSR Validation Dataset
    type: pairedimagedataset
    dataroot_gt: [
      datasets/val/dataset1/hr,
      datasets/val/dataset1/hr2
    ]
    dataroot_lq: [
      datasets/val/dataset1/lr,
      datasets/val/dataset1/lr2
    ]

#####################################################################
# Network Settings
#####################################################################
network_g:
  type: %archname%

network_d:
  type: dunet

#########################################################################################
# Pretrain and Resume Paths
#########################################################################################
path:
  pretrain_network_g: experiments/pretrained_models/pretrain.pth
  param_key_g: ~
  strict_load_g: true
  resume_state: ~

###########################################################################################
# Training Settings with ParagonSR Enhanced Sequence Control
###########################################################################################
train:
  ema_decay: %ema_decay%
  grad_clip: false

  optim_g:
    type: AdamW
    lr: %lr%
    weight_decay: 0
    betas: %betas%
  optim_d:
    type: AdamW
    lr: %lr%
    weight_decay: 0
    betas: %betas%

  scheduler:
    type: MultiStepLR
    milestones: %milestones%
    gamma: 0.5

  total_iter: %total_iter%
  warmup_iter: %warmup_iter%

  #######################################################################
  # Losses
  #######################################################################
  losses:
    # Content Losses
    - type: mssimloss
      loss_weight: 0.5
    - type: perceptualloss
      criterion: charbonnier
      loss_weight: 0.01
    - type: hsluvloss
      criterion: charbonnier
      loss_weight: 1.0
    - type: cosimloss
      loss_weight: 1.0

    # GAN Loss (R3GAN)
    - type: ganloss
      gan_type: r3gan
      loss_weight: 0.1
      r1_weight: 10.0
      r2_weight: 10.0

  #######################################################################
  # ParagonSR Enhanced OTF Degradation Settings with Sequence Control
  #######################################################################

  # Enable OTF processing
  high_order_degradation: true

  # Clean Pass-Through for Identity Learning
  p_clean: 0.1  # 10% chance to pass clean images through

  # =========================================================
  # SEQUENCE CONTROL CONFIGURATION (Added by Philip Hofmann)
  # =========================================================
  enable_sequences: true  # Enable realistic degradation sequences
  sequence_probability: 0.7  # 70% chance to use sequences vs individual degradations

  # Predefined Sequence Configuration
  # These sequences simulate real-world photography workflows
  predefined_sequences:
    internet_upload_download:
      enabled: true
      probability: 0.3  # 30% chance this sequence is selected
      description: "Simulates internet image sharing - user oversharpening → upload compression → download → re-upload"

    phone_camera_capture:
      enabled: true
      probability: 0.25  # 25% chance for phone camera workflow
      description: "Phone camera capture with sensor noise, rolling shutter, lens distortion"

    dslr_professional:
      enabled: true
      probability: 0.2  # 20% chance for professional camera workflow
      description: "DSLR/professional camera with minimal noise and high-quality processing"

    social_media_upload:
      enabled: true
      probability: 0.25  # 25% chance for social media workflow
      description: "Social media upload cycle with aggressive compression and platform processing"

  # Fallback Individual Degradations (when sequences not used)
  # =========================================================

  # Original Real-ESRGAN Degradations (reduced probabilities)
  blur_prob: 0.3  # Lowered since sequences handle many cases
  resize_prob: [0.2, 0.7, 0.1]
  resize_mode_list: ["bilinear", "bicubic", "nearest-exact", "lanczos"]
  resize_mode_prob: [0.25, 0.25, 0.25, 0.25]
  resize_range: [0.4, 1.5]
  gaussian_noise_prob: 0.3  # Lowered
  noise_range: [0, 15]
  gray_noise_prob: 0
  jpeg_prob: 0.4  # Lowered since sequences include compression
  jpeg_range: [75, 95]

  blur_prob2: 0.3
  resize_prob2: [0.3, 0.4, 0.3]
  resize_mode_list2: ["bilinear", "bicubic", "nearest-exact", "lanczos"]
  resize_mode_prob2: [0.25, 0.25, 0.25, 0.25]
  resize_range2: [0.6, 1.2]
  gaussian_noise_prob2: 0.2
  noise_range2: [0, 10]
  gray_noise_prob2: 0
  jpeg_prob2: 0.3
  jpeg_range2: [75, 95]

  resize_mode_list3: ["bilinear", "bicubic", "nearest-exact", "lanczos"]
  resize_mode_prob3: [0.25, 0.25, 0.25, 0.25]

  # Individual Modern Compression Formats (used as fallbacks)
  webp_prob: 0.1  # Lowered - sequences handle most cases
  webp_range: [75, 95]

  avif_prob: 0.05
  avif_range: [75, 95]

  heif_prob: 0.05
  heif_range: [75, 95]

  # Individual Camera Artifacts (used as fallbacks)
  oversharpen_prob: 0.1  # Lowered - sequences handle oversharpening
  oversharpen_strength: [1.0, 2.0]

  chromatic_aberration_prob: 0.05
  demosaic_prob: 0.05
  aliasing_prob: 0.1
  aliasing_scale_range: [0.6, 0.9]

  motion_blur_prob: 0.05  # Lowered - sequences handle motion blur
  motion_blur_kernel_size: [5, 15]
  motion_blur_angle_range: [0, 360]

  lens_distort_prob: 0.05  # Lowered - sequences handle distortion
  lens_distort_strength_range: [-0.3, 0.3]

  exposure_prob: 0.05
  exposure_factor_range: [0.5, 2.0]

  color_temp_prob: 0.05  # Lowered - sequences handle color shifts
  color_temp_shift_range: [-0.2, 0.2]

  sensor_noise_prob: 0.05  # Lowered - sequences handle sensor noise
  sensor_noise_std_range: [0.01, 0.1]

  rolling_shutter_prob: 0.02  # Lowered - sequences handle rolling shutter
  rolling_shutter_strength_range: [-0.1, 0.1]

  #######################################################################
  # Mix of Augmentations (MoA)
  #######################################################################
  use_moa: false
  moa_augs: ['none', 'mixup', 'cutmix', 'resizemix', 'cutblur']
  moa_probs: [0.4, 0.084, 0.084, 0.084, 0.348]
  moa_debug: false
  moa_debug_limit: 100

##############################################################################################
# Validation
##############################################################################################
val:
  val_enabled: false
  val_freq: 1000
  save_img: true
  tile_size: 0
  tile_overlap: 8
  metrics_enabled: true
  metrics:
    topiq:
      type: calculate_topiq

##############################################################################################
# Logging
##############################################################################################
logger:
  print_freq: 100
  save_checkpoint_freq: 1000
  save_checkpoint_format: safetensors
  use_tb_logger: true
